networks:
  inpt-network:

services:
  backend:
    build:
      context: ./inpt-campus-backend
      dockerfile: Dockerfile
    container_name: inpt-campus-backend
    env_file:
      - ./inpt-campus-backend/.env.prod
    networks:
      - inpt-network
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./inpt-campus-frontend
      dockerfile: Dockerfile
      args:
        # UPDATE THIS WITH YOUR ACTUAL DEPLOYED BACKEND URL
        VITE_API_BASE_URL: https://your-backend-domain.com/api
    container_name: inpt-campus-frontend
    ports:
      - "5173:80"
    networks:
      - inpt-network
    depends_on:
      - backend
